[project]
name = "pre-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.5.0",
    "torch>=2.10.0",
    "transformers>=5.1.0",
    "wandb>=0.24.2",
    "zstandard>=0.25.0",
]
